# Description

In this course, you will learn about the procedures for civil suits. Topics to be covered include the scope of a lawsuit, selection of an appropriate forum, presentation of claims and defenses, choice of applicable law, disposition without a trial, and the effect of judgments on future litigation. Other aspects of civil litigation (e.g., discovery, trials, & appeals) are covered in upper-level elective courses. While the course will focus on federal courts, the rules of civil procedure in many states (including North Carolina) are similar.

This course is intended to prepare you for legal practice by developing the knowledge and skill required to recognize and analyze procedural issues in civil litigation, advise clients on those issues and the available options, and draft pleadings and motions.

# Course Materials

## Required

Civil Procedure: An Open-Source Casebook (v.5.0 2026). Available on the course website: [[emfink.net/Quarto_Casebook](https://www.emfink.net/Quarto_Casebook/)]{.mono-font}.

## Suggested

Kevin M. Clermont, _Principles of Civil Procedure_ (West Academic 7th ed. 2024).

# Policies

## Grading

Your final grade for the term will be based on a midterm quiz (20%), a final examination (70%) and class participation (10%). 

## Attendance

Elon Law School has adopted the following attendance policy for all courses:

> The Law School administers a policy that a student maintain regular and punctual class attendance in all courses in which the student is registered, including externships, clinical courses, or simulation courses. Faculty members will give students written notice of their attendance policies before or during the first week of class. These policies may include, but are not limited to: treating late arrivals, early departures, and/or lack of preparation as absences imposing grade or point reductions for absences, including assigning a failing grade or involuntarily withdrawing a student from the class and any other policies that a professor deems appropriate to create a rigorous and professional classroom environment.
> 
> In case of illness or emergency, students may contact the Office of Student and Professional Life, which will then notify the student’s instructors. A student may notify the faculty member directly of a planned absence and should refer to individual faculty members regarding any policy that may apply. In the case of prolonged illness or incapacity, the student should contact the [Office of Student Life](https://www.elon.edu/u/law/students/).

You should let me know (in advance if feasible) if you are unable to attend class, will arrive late, or must leave early. I do not require an explanation of the reason, nor do I require a doctor's note or other documentation.

## Disability Accommodations

For disability accommodation requests, contact the [Office of Academic Accommodations and Accessibility](https://www.elon.edu/u/academics/koenigsberger-learning-center/disabilities-resources/homepage/graduate-student-resources/).

## Honor Code

The Law School [honor code](https://www.elon.edu/u/law/students/honor-code/) applies to all activities related to your law school study, including conduct during class and examinations.

# Schedule & Assignments

### 1\. Foundations of Civil Procedure

- _Clermont_ chap. 1 & 2

#### Monday, August 31

- Foundations of Civil Procedure, _Casebook_ Chap. 1

### 2\. Parties and Claims

- _Clermont_ chap. 6 

#### Wednesday, September 2 

- Permissive Joinder of Claims & Parties, _Casebook_ Chap. 2, §§ 2.1 & 2.2 

#### Friday, September 4 

- Counterclaims, _Casebook_ Chap. 2, § 2.3 

#### Wednesday, September 9 

- Crossclaims, _Casebook_ § Chap. 2, 2.4 

#### Friday, September 11

- Third-Party Defendants & Claims, _Casebook_ Chap. 2, § 2.5 

####  Monday, September 14 

- Required Parties, _Casebook_ Chap. 2, § 2.6 

#### Wednesday, September 16 

- Joinder Wrap-Up